name: DAGs

on:
  push:
    branches:
      - main
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'
    paths:
      - dags/**

  pull_request:
    branches:
      - main
    paths:
      - dags/**

permissions:
  id-token: write
  contents: read
  pull-requests: write

jobs:
  sync:
    name: DAG Sync
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
