name: Infra

on:
  push:
    branches:
      - main
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'
    paths:
      - infra/**
      - .github/workflows/infra.yml

  pull_request:
    branches:
      - main
    paths:
      - infra/**
      - .github/workflows/infra.yml

permissions:
  id-token: write
  contents: read
  pull-requests: write

jobs:
  infra:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
