name: Merge

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read
  pull-requests: write

jobs:
  paths:
    name: Detect changes
    runs-on: ubuntu-latest
    outputs:
      dags: ${{ steps.changes.outputs.dags }}
      infra: ${{ steps.changes.outputs.infra }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Detect changes
        uses: dorny/paths-filter@v3
        id: changes
        with:
          filters: |
            dags:
              - 'dags/**'
              - '.github/workflows/dags.yml'
            infra:
              - 'infra/**'
              - '.github/workflows/infra.yml'

  dags:
    name: DAGs Dev
    runs-on: ubuntu-latest
    needs: paths
    if: needs.paths.outputs.dags == 'true'
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

  infra:
    name: Infra Dev
    runs-on: ubuntu-latest
    needs: paths
    if: needs.paths.outputs.infra == 'true'
    steps:
      - name: Checkout code
        uses: actions/checkout@v3