name: Release

on:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'

permissions:
  id-token: write
  contents: write
  pull-requests: write

jobs:
  paths:
    name: Detect changes
    runs-on: ubuntu-latest
    outputs:
      dags: ${{ steps.changes.outputs.dags }}
      infra: ${{ steps.changes.outputs.infra }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Get Last Tag
        id: last_tag
        run: echo "tag=$(git describe --tags --abbrev=0 HEAD^)" >> $GITHUB_OUTPUT

      - name: Detect changes
        uses: dorny/paths-filter@v3
        id: changes
        with:
          base: ${{ steps.last_tag.outputs.tag }}
          filters: |
            dags:
              - 'dags/**'
            infra:
              - 'infra/**'

  dags:
    name: DAGs Release
    runs-on: ubuntu-latest
    needs: paths
    if: needs.paths.outputs.dags == 'true'
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

  infra:
    name: Infra Release
    runs-on: ubuntu-latest
    needs: paths
    if: needs.paths.outputs.infra == 'true'
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

  release:
    name: Create Release
    runs-on: ubuntu-latest
    needs: [ dags, infra ]
    steps:
      - name: Publish GitHub release
        uses: softprops/action-gh-release@v2
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          generate_release_notes: true